### PR TITLE
Daemonize the node process

### PR DESCRIPTION
**Pull request by eddydu44**
Just have to do : node server.js !

### CODE REVIEW

**Comment by ViktorQvarfordt** [comment]
What is the purpose of this? I don't see the need to daemonize the process.

The convention for managing node web servers is not to daemonize the process in this way, but rather to use a production process manager which also handles restarting the process in case of unhandled exceptions or crashes etc.

If you are looking for a "node process manager", I strongly recommend [pm2](https://github.com/Unitech/pm2).

**Comment by derhuerst** [comment]
For running Node programs in background, there's more suitable tools like [forever](https://github.com/foreverjs/forever#forever) or [pm2](http://pm2.keymetrics.io/). These support watching & restarting the daemon and logging properly.

**Comment by ViktorQvarfordt** [comment]
@derhuerst Thanks for your input! Seems like we all agree. Closing this.

**Comment by eddydu44** [comment]
ok ok I didn't know o-O
I'm trying pm2

**Pull request closed without merging**
